-- Migration: 003_supervisor_tables
-- Description: Tables for supervisor layer - checkpoints and recovery tracking
-- Part of: Phase 3 - Supervisor Layer

-- Checkpoints for recovery (used by persistence/checkpoint.rs)
CREATE TABLE IF NOT EXISTS checkpoints (
    id BIGSERIAL PRIMARY KEY,
    checkpoint_type TEXT NOT NULL,
    component TEXT NOT NULL,
    data JSONB NOT NULL,
    version INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast checkpoint lookups
CREATE INDEX IF NOT EXISTS idx_checkpoints_type_component
    ON checkpoints(checkpoint_type, component);

-- Index for temporal queries
CREATE INDEX IF NOT EXISTS idx_checkpoints_created
    ON checkpoints(created_at DESC);

-- Recovery attempts tracking
CREATE TABLE IF NOT EXISTS recovery_attempts (
    id SERIAL PRIMARY KEY,
    component TEXT NOT NULL,
    checkpoint_id BIGINT REFERENCES checkpoints(id),
    scenario_type TEXT NOT NULL,
    actions_taken JSONB,
    status TEXT NOT NULL DEFAULT 'initiated',
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    error_message TEXT
);

-- Index for component recovery history
CREATE INDEX IF NOT EXISTS idx_recovery_component
    ON recovery_attempts(component);

-- Index for status queries
CREATE INDEX IF NOT EXISTS idx_recovery_status
    ON recovery_attempts(status);

-- Watchdog alerts history (separate from system_events for specialized queries)
CREATE TABLE IF NOT EXISTS watchdog_alerts (
    id BIGSERIAL PRIMARY KEY,
    component TEXT NOT NULL,
    alert_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    message TEXT NOT NULL,
    metadata JSONB,
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_by TEXT,
    acknowledged_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for unacknowledged alerts
CREATE INDEX IF NOT EXISTS idx_watchdog_unack
    ON watchdog_alerts(acknowledged, created_at DESC)
    WHERE acknowledged = FALSE;

-- Index for component alert history
CREATE INDEX IF NOT EXISTS idx_watchdog_component
    ON watchdog_alerts(component, created_at DESC);

-- Component restart history (for restart limit tracking)
CREATE TABLE IF NOT EXISTS component_restarts (
    id SERIAL PRIMARY KEY,
    component_name TEXT NOT NULL,
    restart_reason TEXT,
    success BOOLEAN DEFAULT FALSE,
    duration_ms INT,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for counting recent restarts
CREATE INDEX IF NOT EXISTS idx_restarts_component_time
    ON component_restarts(component_name, created_at DESC);

-- View for active component issues
CREATE OR REPLACE VIEW v_active_issues AS
SELECT
    ch.component_name,
    ch.status,
    ch.last_heartbeat,
    EXTRACT(EPOCH FROM (NOW() - ch.last_heartbeat)) as seconds_since_heartbeat,
    ch.restart_count,
    (SELECT COUNT(*) FROM watchdog_alerts wa
     WHERE wa.component = ch.component_name
     AND wa.acknowledged = FALSE) as unack_alerts
FROM component_heartbeats ch
WHERE ch.status NOT IN ('stopped', 'running')
   OR ch.last_heartbeat < NOW() - INTERVAL '30 seconds';

-- Function to clean old checkpoints (keep last N per component/type)
CREATE OR REPLACE FUNCTION cleanup_old_checkpoints(keep_count INT DEFAULT 10)
RETURNS INT AS $$
DECLARE
    deleted_count INT;
BEGIN
    WITH ranked AS (
        SELECT id, ROW_NUMBER() OVER (
            PARTITION BY checkpoint_type, component
            ORDER BY created_at DESC
        ) as rn
        FROM checkpoints
    )
    DELETE FROM checkpoints
    WHERE id IN (SELECT id FROM ranked WHERE rn > keep_count);

    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Function to clean old recovery attempts (keep last 30 days)
CREATE OR REPLACE FUNCTION cleanup_old_recovery_attempts(days_to_keep INT DEFAULT 30)
RETURNS INT AS $$
DECLARE
    deleted_count INT;
BEGIN
    DELETE FROM recovery_attempts
    WHERE started_at < NOW() - (days_to_keep || ' days')::INTERVAL;

    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Comment on tables
COMMENT ON TABLE checkpoints IS 'State checkpoints for crash recovery';
COMMENT ON TABLE recovery_attempts IS 'History of automated recovery attempts';
COMMENT ON TABLE watchdog_alerts IS 'Alerts generated by watchdog daemon';
COMMENT ON TABLE component_restarts IS 'History of component restart attempts';
