//! Managed strategy runtime spec builders.
//!
//! These builders project deployment/config state into canonical managed
//! runtime TOML so `bootstrap` can stay focused on assembly and path selection.

use rust_decimal::prelude::ToPrimitive;
use rust_decimal::Decimal;
use tracing::{info, warn};

use crate::config::{
    CryptoEntryMode, CryptoTradingConfig, EventEdgeAgentConfig, NbaComebackConfig,
};
#[cfg(test)]
use crate::config::{PoliticsTradingConfig, SportsTradingConfig};
use crate::error::{PloyError, Result};
use crate::plugins::projector::ProjectedRuntimeSpec;
#[cfg(test)]
use crate::plugins::projector;
#[cfg(test)]
use crate::plugins::{
    ComposableCryptoSpec, DeploymentState as PluginDeploymentState, PluginDefinition,
    PluginDeployment, PluginKind, PluginSpec, RegisteredStrategySpec,
};
#[cfg(test)]
use crate::platform::Domain;

use super::bootstrap::{coin_symbol_for, crypto_series_id_for};

pub(crate) type ManagedStrategyBootstrapSpec = ProjectedRuntimeSpec;

#[cfg(test)]
fn plugin_definition(plugin_id: &str, kind: PluginKind, domain: Domain) -> PluginDefinition {
    PluginDefinition {
        plugin_id: plugin_id.to_string(),
        kind,
        version: "v1".to_string(),
        domain,
    }
}

#[cfg(test)]
fn plugin_deployment(plugin_id: &str, deployment_id: &str) -> PluginDeployment {
    PluginDeployment {
        deployment_id: deployment_id.to_string(),
        plugin_id: plugin_id.to_string(),
        account_id: "default".to_string(),
        state: PluginDeploymentState::Enabled,
    }
}

pub(crate) fn build_pattern_memory_runtime_config(coins: &[String]) -> Result<String> {
    let mut selected: Vec<String> = coins
        .iter()
        .filter_map(|c| {
            c.strip_suffix("USDT")
                .map(|s| s.to_string())
                .or_else(|| Some(c.clone()))
        })
        .map(|c| c.to_ascii_uppercase())
        .collect();
    selected.sort();
    selected.dedup();

    let mut markets_block = String::new();
    for coin in selected {
        if let (Some(symbol), Some(series_id)) =
            (coin_symbol_for(&coin), crypto_series_id_for(&coin, "5m"))
        {
            markets_block.push_str("\n[[markets]]\n");
            markets_block.push_str(&format!("symbol = \"{}\"\n", symbol));
            markets_block.push_str(&format!("series_id = \"{}\"\n", series_id));
        }
    }

    if markets_block.trim().is_empty() {
        return Err(PloyError::Validation(
            "pattern_memory runtime has no recognized crypto coins/series ids".to_string(),
        ));
    }

    Ok(format!(
        r#"# Auto-generated by platform bootstrap
[strategy]
name = "pattern_memory"
enabled = true
{markets}
[pattern]
corr_threshold = 0.70
alpha = 1.0
beta = 1.0
min_matches = 3
min_n_eff = 2.0
min_confidence = 0.60

[filter_15m]
enabled = true
min_confidence = 0.55
min_n_eff = 1.0

[timing]
target_remaining_secs = 300
tolerance_secs = 45
min_remaining_secs = 60

[trade]
shares = 100
max_entry_price = 0.55
min_net_ev = 0.0
cooldown_secs = 30
"#,
        markets = markets_block
    ))
}

fn insert_toml_float(table: &mut toml::value::Table, key: &str, value: f64) {
    table.insert(key.to_string(), toml::Value::Float(value));
}

fn insert_toml_int(table: &mut toml::value::Table, key: &str, value: i64) {
    table.insert(key.to_string(), toml::Value::Integer(value));
}

fn insert_toml_bool(table: &mut toml::value::Table, key: &str, value: bool) {
    table.insert(key.to_string(), toml::Value::Boolean(value));
}

fn render_momentum_runtime_config(
    mut config: toml::Value,
    symbols: &[String],
    crypto_cfg: &CryptoTradingConfig,
) -> String {
    let root = config
        .as_table_mut()
        .expect("momentum runtime config must be a table");
    let strategy = root
        .entry("strategy")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[strategy] must be a table");
    insert_toml_bool(strategy, "enabled", true);

    let entry = root
        .entry("entry")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[entry] must be a table");
    entry.insert(
        "symbols".to_string(),
        toml::Value::Array(symbols.iter().cloned().map(toml::Value::String).collect()),
    );
    insert_toml_float(
        entry,
        "min_move",
        (crypto_cfg.min_momentum_1s * 100.0).max(0.0),
    );
    insert_toml_float(
        entry,
        "min_edge",
        (crypto_cfg.min_edge * Decimal::from(100))
            .to_f64()
            .unwrap_or(2.0),
    );
    insert_toml_bool(
        entry,
        "require_mtf_agreement",
        crypto_cfg.require_mtf_agreement,
    );
    insert_toml_bool(
        entry,
        "directional_mode",
        matches!(crypto_cfg.entry_mode, CryptoEntryMode::Directional),
    );
    insert_toml_float(
        entry,
        "directional_entry_threshold",
        (crypto_cfg.min_edge * Decimal::from(100))
            .to_f64()
            .unwrap_or(2.0),
    );

    let timing = root
        .entry("timing")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[timing] must be a table");
    insert_toml_int(
        timing,
        "min_time_remaining",
        crypto_cfg.min_time_remaining_secs as i64,
    );
    insert_toml_int(
        timing,
        "max_time_remaining",
        crypto_cfg.max_time_remaining_secs as i64,
    );
    insert_toml_int(
        timing,
        "cooldown_secs",
        crypto_cfg.entry_cooldown_secs as i64,
    );

    let risk = root
        .entry("risk")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[risk] must be a table");
    insert_toml_int(risk, "shares", crypto_cfg.default_shares as i64);
    insert_toml_int(
        risk,
        "max_positions",
        crypto_cfg.risk_params.max_unhedged_positions as i64,
    );
    insert_toml_float(
        risk,
        "max_window_exposure",
        crypto_cfg
            .risk_params
            .max_total_exposure
            .to_f64()
            .unwrap_or(25.0),
    );

    let exit = root
        .entry("exit")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[exit] must be a table");
    insert_toml_float(
        exit,
        "exit_edge_floor_pct",
        (crypto_cfg.exit_edge_floor * Decimal::from(100))
            .to_f64()
            .unwrap_or(20.0),
    );
    insert_toml_float(
        exit,
        "exit_price_band_pct",
        (crypto_cfg.exit_price_band * Decimal::from(100))
            .to_f64()
            .unwrap_or(12.0),
    );

    format!(
        "# Auto-generated by platform bootstrap — momentum\n{}",
        toml::to_string(&config).expect("runtime config must serialize to TOML")
    )
}

fn load_momentum_config_file(symbols: &[String], crypto_cfg: &CryptoTradingConfig) -> Option<String> {
    let candidates = [
        std::env::var("PLOY_MOMENTUM_CONFIG").ok(),
        Some("config/strategies/momentum.toml".to_string()),
        Some("/root/ploy/config/strategies/momentum.toml".to_string()),
        Some("/opt/ploy/config/strategies/momentum.toml".to_string()),
    ];
    for candidate in candidates.iter().flatten() {
        if let Ok(contents) = std::fs::read_to_string(candidate) {
            if let Ok(val) = toml::from_str::<toml::Value>(&contents) {
                if val.get("strategy").is_some() {
                    info!(path = %candidate, "loaded momentum config from external file");
                    return Some(render_momentum_runtime_config(val, symbols, crypto_cfg));
                }
            }
            warn!(path = %candidate, "momentum config file found but invalid TOML");
        }
    }
    None
}

pub(crate) fn build_momentum_runtime_config(
    symbols: &[String],
    crypto_cfg: &CryptoTradingConfig,
) -> String {
    if let Some(cfg) = load_momentum_config_file(symbols, crypto_cfg) {
        return cfg;
    }

    let config: toml::Value = toml::from_str(include_str!("../../config/strategies/momentum.toml"))
        .expect("embedded momentum runtime config must stay valid TOML");
    render_momentum_runtime_config(config, symbols, crypto_cfg)
}

pub(crate) fn build_event_edge_runtime_config(
    rest_url: &str,
    cfg: &EventEdgeAgentConfig,
) -> String {
    let mut root = toml::value::Table::new();

    let mut strategy = toml::value::Table::new();
    strategy.insert("name".to_string(), toml::Value::String("event_edge".to_string()));
    strategy.insert("enabled".to_string(), toml::Value::Boolean(cfg.enabled));
    strategy.insert("trade".to_string(), toml::Value::Boolean(cfg.trade));
    root.insert("strategy".to_string(), toml::Value::Table(strategy));

    let mut events = toml::value::Table::new();
    events.insert(
        "event_ids".to_string(),
        toml::Value::Array(
            cfg.event_ids
                .iter()
                .cloned()
                .map(toml::Value::String)
                .collect(),
        ),
    );
    events.insert(
        "titles".to_string(),
        toml::Value::Array(
            cfg.titles
                .iter()
                .cloned()
                .map(toml::Value::String)
                .collect(),
        ),
    );
    root.insert("events".to_string(), toml::Value::Table(events));

    let mut entry = toml::value::Table::new();
    insert_toml_float(&mut entry, "min_edge", cfg.min_edge.to_f64().unwrap_or(0.08));
    insert_toml_float(&mut entry, "max_entry", cfg.max_entry.to_f64().unwrap_or(0.75));
    insert_toml_int(&mut entry, "shares", cfg.shares as i64);
    root.insert("entry".to_string(), toml::Value::Table(entry));

    let mut timing = toml::value::Table::new();
    insert_toml_int(&mut timing, "poll_interval_secs", cfg.interval_secs as i64);
    root.insert("timing".to_string(), toml::Value::Table(timing));

    let mut risk = toml::value::Table::new();
    insert_toml_int(&mut risk, "cooldown_secs", cfg.cooldown_secs as i64);
    insert_toml_float(
        &mut risk,
        "max_daily_spend_usd",
        cfg.max_daily_spend_usd.to_f64().unwrap_or(100.0),
    );
    root.insert("risk".to_string(), toml::Value::Table(risk));

    let mut polymarket = toml::value::Table::new();
    polymarket.insert(
        "rest_url".to_string(),
        toml::Value::String(rest_url.to_string()),
    );
    root.insert("polymarket".to_string(), toml::Value::Table(polymarket));

    format!(
        "# Auto-generated by platform bootstrap — event edge\n{}",
        toml::to_string(&toml::Value::Table(root))
            .expect("event edge runtime config must serialize to TOML")
    )
}

#[cfg(test)]
pub(crate) fn build_momentum_managed_runtime_spec(
    symbols: &[String],
    crypto_cfg: &CryptoTradingConfig,
) -> ManagedStrategyBootstrapSpec {
    projector::project_momentum_runtime_spec(
        &plugin_definition(
            "crypto.momentum.v1",
            PluginKind::ComposableCrypto,
            Domain::Crypto,
        ),
        &PluginSpec::ComposableCrypto(ComposableCryptoSpec {
            signal_blocks: vec!["momentum".to_string()],
        }),
        &plugin_deployment(
            "crypto.momentum.v1",
            &format!("managed-runtime.{}", crypto_cfg.agent_id),
        ),
        symbols,
        crypto_cfg,
    )
    .expect("momentum plugin projection must stay valid")
}

#[cfg(test)]
pub(crate) fn build_event_edge_managed_runtime_spec(
    rest_url: &str,
    politics_cfg: &PoliticsTradingConfig,
    ee_cfg: &EventEdgeAgentConfig,
) -> ManagedStrategyBootstrapSpec {
    projector::project_event_edge_runtime_spec(
        &plugin_definition(
            "politics.event_edge.v1",
            PluginKind::RegisteredStrategy,
            Domain::Politics,
        ),
        &PluginSpec::RegisteredStrategy(RegisteredStrategySpec {
            strategy_name: "event_edge".to_string(),
        }),
        &plugin_deployment(
            "politics.event_edge.v1",
            &format!("managed-runtime.{}", politics_cfg.agent_id),
        ),
        rest_url,
        politics_cfg,
        ee_cfg,
    )
    .expect("event_edge plugin projection must stay valid")
}

pub(crate) fn build_nba_comeback_runtime_config(
    database_url: &str,
    cfg: &NbaComebackConfig,
) -> String {
    let mut root = toml::value::Table::new();

    let mut strategy = toml::value::Table::new();
    strategy.insert(
        "name".to_string(),
        toml::Value::String("nba_comeback".to_string()),
    );
    strategy.insert("enabled".to_string(), toml::Value::Boolean(cfg.enabled));
    root.insert("strategy".to_string(), toml::Value::Table(strategy));

    let mut entry = toml::value::Table::new();
    insert_toml_float(&mut entry, "min_edge", cfg.min_edge.to_f64().unwrap_or(0.05));
    insert_toml_float(
        &mut entry,
        "max_entry_price",
        cfg.max_entry_price.to_f64().unwrap_or(0.75),
    );
    insert_toml_int(&mut entry, "shares", cfg.shares as i64);
    root.insert("entry".to_string(), toml::Value::Table(entry));

    let mut timing = toml::value::Table::new();
    insert_toml_int(
        &mut timing,
        "poll_interval_secs",
        cfg.espn_poll_interval_secs as i64,
    );
    root.insert("timing".to_string(), toml::Value::Table(timing));

    let mut risk = toml::value::Table::new();
    insert_toml_int(&mut risk, "cooldown_secs", cfg.cooldown_secs as i64);
    insert_toml_float(
        &mut risk,
        "max_daily_spend_usd",
        cfg.max_daily_spend_usd.to_f64().unwrap_or(100.0),
    );
    insert_toml_float(
        &mut risk,
        "min_reward_risk_ratio",
        cfg.min_reward_risk_ratio,
    );
    insert_toml_float(&mut risk, "min_expected_value", cfg.min_expected_value);
    insert_toml_float(&mut risk, "kelly_fraction_cap", cfg.kelly_fraction_cap);
    root.insert("risk".to_string(), toml::Value::Table(risk));

    let mut scan = toml::value::Table::new();
    insert_toml_int(&mut scan, "min_deficit", cfg.min_deficit as i64);
    insert_toml_int(&mut scan, "max_deficit", cfg.max_deficit as i64);
    insert_toml_int(&mut scan, "target_quarter", cfg.target_quarter as i64);
    insert_toml_float(&mut scan, "min_comeback_rate", cfg.min_comeback_rate);
    scan.insert("season".to_string(), toml::Value::String(cfg.season.clone()));
    root.insert("scan".to_string(), toml::Value::Table(scan));

    let mut database = toml::value::Table::new();
    database.insert(
        "url".to_string(),
        toml::Value::String(database_url.to_string()),
    );
    root.insert("database".to_string(), toml::Value::Table(database));

    let mut grok = toml::value::Table::new();
    grok.insert("enabled".to_string(), toml::Value::Boolean(cfg.grok_enabled));
    insert_toml_int(&mut grok, "interval_secs", cfg.grok_interval_secs as i64);
    insert_toml_float(
        &mut grok,
        "min_edge",
        cfg.grok_min_edge.to_f64().unwrap_or(0.08),
    );
    insert_toml_float(&mut grok, "min_confidence", cfg.grok_min_confidence);
    insert_toml_int(
        &mut grok,
        "decision_cooldown_secs",
        cfg.grok_decision_cooldown_secs as i64,
    );
    grok.insert(
        "fallback_enabled".to_string(),
        toml::Value::Boolean(cfg.grok_fallback_enabled),
    );
    root.insert("grok".to_string(), toml::Value::Table(grok));

    let mut performance = toml::value::Table::new();
    insert_toml_float(
        &mut performance,
        "daily_loss_limit_usd",
        cfg.performance_daily_loss_limit_usd.to_f64().unwrap_or(30.0),
    );
    insert_toml_int(
        &mut performance,
        "min_settled_trades",
        cfg.performance_min_settled_trades as i64,
    );
    insert_toml_float(
        &mut performance,
        "min_win_rate",
        cfg.performance_min_win_rate,
    );
    insert_toml_float(
        &mut performance,
        "low_winrate_multiplier",
        cfg.performance_low_winrate_multiplier,
    );
    insert_toml_int(
        &mut performance,
        "loss_streak_threshold",
        cfg.performance_loss_streak_threshold as i64,
    );
    insert_toml_float(
        &mut performance,
        "loss_streak_multiplier",
        cfg.performance_loss_streak_multiplier,
    );
    root.insert("performance".to_string(), toml::Value::Table(performance));

    let mut scaling = toml::value::Table::new();
    scaling.insert(
        "enabled".to_string(),
        toml::Value::Boolean(cfg.scaling_enabled),
    );
    insert_toml_int(&mut scaling, "max_adds", cfg.scaling_max_adds as i64);
    insert_toml_float(
        &mut scaling,
        "min_price_drop_pct",
        cfg.scaling_min_price_drop_pct,
    );
    insert_toml_float(
        &mut scaling,
        "max_game_exposure_usd",
        cfg.scaling_max_game_exposure_usd.to_f64().unwrap_or(50.0),
    );
    insert_toml_float(
        &mut scaling,
        "min_comeback_retention",
        cfg.scaling_min_comeback_retention,
    );
    insert_toml_float(
        &mut scaling,
        "min_time_remaining_mins",
        cfg.scaling_min_time_remaining_mins,
    );
    root.insert("scaling".to_string(), toml::Value::Table(scaling));

    let mut exit = toml::value::Table::new();
    exit.insert(
        "enabled".to_string(),
        toml::Value::Boolean(cfg.early_exit_enabled),
    );
    insert_toml_float(
        &mut exit,
        "take_profit_pct",
        cfg.early_exit_take_profit_pct,
    );
    insert_toml_float(
        &mut exit,
        "stop_loss_pct",
        cfg.early_exit_stop_loss_pct,
    );
    root.insert("exit".to_string(), toml::Value::Table(exit));

    format!(
        "# Auto-generated by platform bootstrap — nba comeback\n{}",
        toml::to_string(&toml::Value::Table(root))
            .expect("nba comeback runtime config must serialize to TOML")
    )
}

#[cfg(test)]
pub(crate) fn build_nba_comeback_managed_runtime_spec(
    database_url: &str,
    sports_cfg: &SportsTradingConfig,
    nba_cfg: &NbaComebackConfig,
) -> ManagedStrategyBootstrapSpec {
    projector::project_nba_comeback_runtime_spec(
        &plugin_definition(
            "sports.nba_comeback.v1",
            PluginKind::RegisteredStrategy,
            Domain::Sports,
        ),
        &PluginSpec::RegisteredStrategy(RegisteredStrategySpec {
            strategy_name: "nba_comeback".to_string(),
        }),
        &plugin_deployment(
            "sports.nba_comeback.v1",
            &format!("managed-runtime.{}", sports_cfg.agent_id),
        ),
        database_url,
        sports_cfg,
        nba_cfg,
    )
    .expect("nba_comeback plugin projection must stay valid")
}

fn render_split_arb_runtime_config(
    mut config: toml::Value,
    symbols: &[String],
    series_ids: &[String],
) -> String {
    let root = config
        .as_table_mut()
        .expect("staggered_arb runtime config must be a table");
    let strategy = root
        .entry("strategy")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[strategy] must be a table");
    strategy.insert("enabled".to_string(), toml::Value::Boolean(true));

    let entry = root
        .entry("entry")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[entry] must be a table");
    entry.insert(
        "symbols".to_string(),
        toml::Value::Array(symbols.iter().cloned().map(toml::Value::String).collect()),
    );

    let markets = root
        .entry("markets")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[markets] must be a table");
    markets.insert(
        "series_ids".to_string(),
        toml::Value::Array(
            series_ids
                .iter()
                .cloned()
                .map(toml::Value::String)
                .collect(),
        ),
    );

    format!(
        "# Auto-generated by platform bootstrap — staggered arb (時間差套利)\n{}",
        toml::to_string(&config).expect("runtime config must serialize to TOML")
    )
}

fn load_split_arb_config_file(symbols: &[String], series_ids: &[String]) -> Option<String> {
    let candidates = [
        std::env::var("PLOY_STAGGERED_ARB_CONFIG").ok(),
        Some("config/strategies/staggered_arb.toml".to_string()),
        Some("/root/ploy/config/strategies/staggered_arb.toml".to_string()),
        Some("/opt/ploy/config/strategies/staggered_arb.toml".to_string()),
    ];
    for candidate in candidates.iter().flatten() {
        if let Ok(contents) = std::fs::read_to_string(candidate) {
            if let Ok(val) = toml::from_str::<toml::Value>(&contents) {
                if val.get("strategy").is_some() {
                    info!(
                        path = %candidate,
                        "loaded staggered_arb config from external file"
                    );
                    return Some(render_split_arb_runtime_config(val, symbols, series_ids));
                }
            }
            warn!(path = %candidate, "staggered_arb config file found but invalid TOML");
        }
    }
    None
}

pub(crate) fn build_split_arb_runtime_config(symbols: &[String], series_ids: &[String]) -> String {
    if let Some(cfg) = load_split_arb_config_file(symbols, series_ids) {
        return cfg;
    }

    let config: toml::Value =
        toml::from_str(include_str!("../../config/strategies/staggered_arb.toml"))
            .expect("embedded staggered_arb runtime config must stay valid TOML");
    render_split_arb_runtime_config(config, symbols, series_ids)
}

#[cfg(test)]
pub(crate) fn build_split_arb_managed_runtime_spec(
    symbols: &[String],
    series_ids: &[String],
) -> ManagedStrategyBootstrapSpec {
    projector::project_split_arb_runtime_spec(
        &plugin_definition(
            "crypto.split_arb.v1",
            PluginKind::ComposableCrypto,
            Domain::Crypto,
        ),
        &PluginSpec::ComposableCrypto(ComposableCryptoSpec {
            signal_blocks: vec!["split_arb".to_string()],
        }),
        &plugin_deployment("crypto.split_arb.v1", "managed-runtime.split_arb"),
        symbols,
        series_ids,
    )
    .expect("split_arb plugin projection must stay valid")
}
