import { createSdkMcpServer, tool } from "@anthropic-ai/claude-agent-sdk";
import { z } from "zod";
import { appendHarnessProposal } from "../runtime/harness-memory.js";
import {
  applyApprovedSelfModification,
  dispatchApprovedSelfModificationDeployment,
  dispatchApprovedSelfModificationRollback,
  proposeSelfModification,
} from "../runtime/self-modification.js";

const workflowInputSchema = z.record(z.string(), z.union([z.string(), z.number(), z.boolean()]));

export const agentRuntimeServer = createSdkMcpServer({
  name: "agent-runtime",
  version: "1.0.0",
  tools: [
    tool(
      "complete_task",
      "Signal that the current agent run has reached success, partial completion, or a blocker.",
      {
        status: z.enum(["success", "partial", "blocked"]).default("success"),
        summary: z.string().describe("Concise operator-facing completion summary"),
        decision: z
          .enum(["continue", "pass", "trade", "monitor", "blocked"])
          .optional()
          .describe("Final operator decision, if one was reached"),
        grok_decision: z
          .enum(["trade", "pass", "not_queried"])
          .optional()
          .describe("Required for Grok Builder contracts"),
        evidence: z
          .array(z.string())
          .default([])
          .describe("Short evidence bullets that justify the completion status"),
        blockers: z
          .array(z.string())
          .default([])
          .describe("Concrete blockers when status is partial or blocked"),
        next_action: z.string().optional().describe("Single next action for the operator or retry loop"),
      },
      async ({ status, summary, decision, grok_decision, evidence, blockers, next_action }) => ({
        content: [
          {
            type: "text" as const,
            text: JSON.stringify({
              status,
              summary,
              decision,
              grok_decision,
              evidence,
              blockers,
              next_action,
            }),
          },
        ],
      })
    ),
    tool(
      "propose_harness_improvement",
      "Record a non-code harness improvement proposal for future human review.",
      {
        category: z.enum([
          "completion_gap",
          "tool_gap",
          "runtime_error",
          "approval_gate",
          "negative_result",
        ]),
        summary: z.string().describe("What failed or could improve"),
        suggested_change: z.string().describe("Smallest proposed harness/prompt/profile change"),
        subagent_profile: z.string().optional().describe("Optional proposed subagent/profile name"),
      },
      async ({ category, summary, suggested_change, subagent_profile }) => {
        const proposal = await appendHarnessProposal({
          category,
          summary,
          suggested_change,
          subagent_profile,
        });
        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify(proposal),
            },
          ],
        };
      }
    ),
    tool(
      "propose_self_modification",
      "Record a patch proposal for approval-gated harness self-modification.",
      {
        title: z.string(),
        patch: z.string().describe("Unified git patch generated by git diff"),
        verification_command: z.string().optional(),
      },
      async ({ title, patch, verification_command }) => {
        const proposal = await proposeSelfModification({
          title,
          patch,
          verification_command,
        });
        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify(proposal),
            },
          ],
        };
      }
    ),
    tool(
      "apply_self_modification",
      "Apply an approved harness self-modification proposal with rollback on verification failure, optionally publishing a PR.",
      {
        proposal_id: z.string(),
        approval_token: z.string(),
        publish_pull_request: z.boolean().default(false),
        branch_name: z.string().optional(),
        commit_message: z.string().optional(),
        pull_request_title: z.string().optional(),
        pull_request_body: z.string().optional(),
        base_branch: z.string().optional(),
      },
      async ({
        proposal_id,
        approval_token,
        publish_pull_request,
        branch_name,
        commit_message,
        pull_request_title,
        pull_request_body,
        base_branch,
      }) => {
        const result = await applyApprovedSelfModification({
          proposal_id,
          approval_token,
          publish_pull_request,
          branch_name,
          commit_message,
          pull_request_title,
          pull_request_body,
          base_branch,
        });
        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify(result),
            },
          ],
        };
      }
    ),
    tool(
      "dispatch_self_modification_deployment",
      "Dispatch an allowlisted GitHub Actions deployment workflow after approval, with a required rollback workflow gate.",
      {
        approval_token: z.string(),
        workflow: z.string().describe("Allowlisted workflow file, for example deploy-tango-1-1.yml"),
        workflow_ref: z.string().default("main"),
        inputs: workflowInputSchema.default({}),
        rollback_workflow: z.string().describe("Allowlisted workflow file to use for rollback"),
        rollback_workflow_ref: z.string().default("main"),
        rollback_inputs: workflowInputSchema.default({}),
      },
      async ({
        approval_token,
        workflow,
        workflow_ref,
        inputs,
        rollback_workflow,
        rollback_workflow_ref,
        rollback_inputs,
      }) => {
        const result = await dispatchApprovedSelfModificationDeployment({
          approval_token,
          workflow,
          workflow_ref,
          inputs,
          rollback_workflow,
          rollback_workflow_ref,
          rollback_inputs,
        });
        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify(result),
            },
          ],
        };
      }
    ),
    tool(
      "dispatch_self_modification_rollback",
      "Dispatch an allowlisted GitHub Actions rollback workflow after approval.",
      {
        approval_token: z.string(),
        workflow: z.string(),
        workflow_ref: z.string().default("main"),
        inputs: workflowInputSchema.default({}),
      },
      async ({ approval_token, workflow, workflow_ref, inputs }) => {
        const result = await dispatchApprovedSelfModificationRollback({
          approval_token,
          workflow,
          workflow_ref,
          inputs,
        });
        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify(result),
            },
          ],
        };
      }
    ),
  ],
});
