use rust_decimal::prelude::ToPrimitive;
use tracing::{info, warn};

use crate::config::{EventEdgeAgentConfig, NbaComebackConfig};
use crate::error::{PloyError, Result};
use crate::strategy::crypto_lob_ml::CryptoLobMlConfig;
#[cfg(feature = "rl")]
use crate::strategy::crypto_rl_policy::CryptoRlPolicyConfig;
use crate::strategy::CryptoTradingConfig;

use super::deployment_matrix::{coin_symbol_for, crypto_series_id_for};

fn set_integer(table: &mut toml::map::Map<String, toml::Value>, key: &str, value: i64) {
    table.insert(key.to_string(), toml::Value::Integer(value));
}

fn set_float(table: &mut toml::map::Map<String, toml::Value>, key: &str, value: f64) {
    table.insert(key.to_string(), toml::Value::Float(value));
}

fn set_decimal(
    table: &mut toml::map::Map<String, toml::Value>,
    key: &str,
    value: rust_decimal::Decimal,
) {
    set_float(table, key, value.to_f64().unwrap_or(0.0));
}

fn set_bool(table: &mut toml::map::Map<String, toml::Value>, key: &str, value: bool) {
    table.insert(key.to_string(), toml::Value::Boolean(value));
}

fn set_string(
    table: &mut toml::map::Map<String, toml::Value>,
    key: &str,
    value: impl Into<String>,
) {
    table.insert(key.to_string(), toml::Value::String(value.into()));
}

fn set_string_array(table: &mut toml::map::Map<String, toml::Value>, key: &str, values: &[String]) {
    table.insert(
        key.to_string(),
        toml::Value::Array(values.iter().cloned().map(toml::Value::String).collect()),
    );
}

fn normalize_runtime_symbols(values: &[String]) -> Vec<String> {
    let mut symbols: Vec<String> = values
        .iter()
        .filter_map(|value| {
            let trimmed = value.trim();
            if trimmed.is_empty() {
                return None;
            }
            let upper = trimmed.to_ascii_uppercase();
            if upper.ends_with("USDT") {
                Some(upper)
            } else {
                coin_symbol_for(&upper)
            }
        })
        .collect();
    symbols.sort();
    symbols.dedup();
    symbols
}

pub(crate) fn build_pattern_memory_runtime_config(coins: &[String]) -> Result<String> {
    let mut selected: Vec<String> = coins
        .iter()
        .filter_map(|c| {
            c.strip_suffix("USDT")
                .map(|s| s.to_string())
                .or_else(|| Some(c.clone()))
        })
        .map(|c| c.to_ascii_uppercase())
        .collect();
    selected.sort();
    selected.dedup();

    let mut markets_block = String::new();
    for coin in selected {
        if let (Some(symbol), Some(series_id)) =
            (coin_symbol_for(&coin), crypto_series_id_for(&coin, "5m"))
        {
            markets_block.push_str("\n[[markets]]\n");
            markets_block.push_str(&format!("symbol = \"{symbol}\"\n"));
            markets_block.push_str(&format!("series_id = \"{series_id}\"\n"));
        }
    }

    if markets_block.trim().is_empty() {
        return Err(PloyError::Validation(
            "pattern_memory runtime has no recognized crypto coins/series ids".to_string(),
        ));
    }

    Ok(format!(
        r#"# Auto-generated by platform bootstrap
[strategy]
name = "pattern_memory"
enabled = true
{markets}
[pattern]
corr_threshold = 0.70
alpha = 1.0
beta = 1.0
min_matches = 3
min_n_eff = 2.0
min_confidence = 0.60

[filter_15m]
enabled = true
min_confidence = 0.55
min_n_eff = 1.0

[timing]
target_remaining_secs = 300
tolerance_secs = 45
min_remaining_secs = 60

[trade]
shares = 100
max_entry_price = 0.55
min_net_ev = 0.0
cooldown_secs = 30
"#,
        markets = markets_block
    ))
}

pub(crate) fn build_crypto_lob_ml_runtime_config(cfg: &CryptoLobMlConfig) -> Result<String> {
    if cfg.coins.is_empty() {
        return Err(PloyError::Validation(
            "crypto_lob_ml runtime requires at least one configured coin".to_string(),
        ));
    }

    let mut root = toml::map::Map::new();
    let mut strategy = toml::map::Map::new();
    let mut lob_ml = toml::map::Map::new();

    let mut coins: Vec<String> = cfg
        .coins
        .iter()
        .map(|coin| coin.to_ascii_uppercase())
        .collect();
    coins.sort();
    coins.dedup();

    set_string(&mut strategy, "name", "crypto_lob_ml");
    set_bool(&mut strategy, "enabled", true);

    set_string_array(&mut lob_ml, "coins", &coins);
    set_integer(
        &mut lob_ml,
        "min_time_remaining_secs",
        i64::try_from(cfg.min_time_remaining_secs).unwrap_or(60),
    );
    set_integer(
        &mut lob_ml,
        "max_time_remaining_secs",
        i64::try_from(cfg.max_time_remaining_secs).unwrap_or(900),
    );
    set_integer(
        &mut lob_ml,
        "max_time_remaining_secs_5m",
        i64::try_from(cfg.max_time_remaining_secs_5m).unwrap_or(120),
    );
    set_integer(
        &mut lob_ml,
        "max_time_remaining_secs_15m",
        i64::try_from(cfg.max_time_remaining_secs_15m).unwrap_or(240),
    );
    set_bool(
        &mut lob_ml,
        "require_price_to_beat",
        cfg.require_price_to_beat,
    );
    set_integer(
        &mut lob_ml,
        "max_lob_snapshot_age_secs",
        i64::try_from(cfg.max_lob_snapshot_age_secs).unwrap_or(2),
    );
    set_integer(&mut lob_ml, "tick_interval_ms", 1000);

    root.insert("strategy".to_string(), toml::Value::Table(strategy));
    root.insert("crypto_lob_ml".to_string(), toml::Value::Table(lob_ml));
    toml::to_string_pretty(&toml::Value::Table(root)).map_err(|e| {
        PloyError::Internal(format!(
            "failed to render crypto_lob_ml runtime config: {e}"
        ))
    })
}

#[cfg(feature = "rl")]
pub(crate) fn build_crypto_rl_policy_runtime_config(cfg: &CryptoRlPolicyConfig) -> Result<String> {
    if cfg.coins.is_empty() {
        return Err(PloyError::Validation(
            "crypto_rl_policy runtime requires at least one configured coin".to_string(),
        ));
    }

    let mut root = toml::map::Map::new();
    let mut strategy = toml::map::Map::new();
    let mut rl_policy = toml::map::Map::new();

    let mut coins: Vec<String> = cfg
        .coins
        .iter()
        .map(|coin| coin.to_ascii_uppercase())
        .collect();
    coins.sort();
    coins.dedup();

    set_string(&mut strategy, "name", "crypto_rl_policy");
    set_bool(&mut strategy, "enabled", true);

    set_string_array(&mut rl_policy, "coins", &coins);
    set_integer(
        &mut rl_policy,
        "min_time_remaining_secs",
        i64::try_from(cfg.min_time_remaining_secs).unwrap_or(60),
    );
    set_integer(
        &mut rl_policy,
        "max_time_remaining_secs",
        i64::try_from(cfg.max_time_remaining_secs).unwrap_or(900),
    );
    set_integer(
        &mut rl_policy,
        "default_shares",
        i64::try_from(cfg.default_shares).unwrap_or(50),
    );
    set_decimal(&mut rl_policy, "max_entry_price", cfg.max_entry_price);
    set_integer(
        &mut rl_policy,
        "max_lob_snapshot_age_secs",
        i64::try_from(cfg.max_lob_snapshot_age_secs).unwrap_or(2),
    );
    set_integer(
        &mut rl_policy,
        "tick_interval_ms",
        i64::try_from(cfg.decision_interval_ms).unwrap_or(1000),
    );
    set_integer(
        &mut rl_policy,
        "observation_version",
        i64::from(cfg.observation_version),
    );
    set_string(&mut rl_policy, "policy_output", cfg.policy_output.clone());
    if let Some(path) = cfg.policy_model_path.as_deref() {
        if !path.trim().is_empty() {
            set_string(&mut rl_policy, "policy_model_path", path.to_string());
        }
    }
    if let Some(version) = cfg.policy_model_version.as_deref() {
        if !version.trim().is_empty() {
            set_string(&mut rl_policy, "policy_model_version", version.to_string());
        }
    }

    root.insert("strategy".to_string(), toml::Value::Table(strategy));
    root.insert(
        "crypto_rl_policy".to_string(),
        toml::Value::Table(rl_policy),
    );
    toml::to_string_pretty(&toml::Value::Table(root)).map_err(|e| {
        PloyError::Internal(format!(
            "failed to render crypto_rl_policy runtime config: {e}"
        ))
    })
}

pub(crate) fn build_event_edge_runtime_config(cfg: &EventEdgeAgentConfig) -> Result<String> {
    if cfg.event_ids.is_empty() && cfg.titles.is_empty() {
        return Err(PloyError::Validation(
            "event_edge runtime requires at least one event_id or title target".to_string(),
        ));
    }

    let mut root = toml::map::Map::new();
    let mut strategy = toml::map::Map::new();
    let mut event_edge = toml::map::Map::new();

    set_string(&mut strategy, "name", "event_edge");
    set_bool(&mut strategy, "enabled", true);

    set_string(&mut event_edge, "framework", cfg.framework.clone());
    set_string_array(&mut event_edge, "event_ids", &cfg.event_ids);
    set_string_array(&mut event_edge, "titles", &cfg.titles);
    set_integer(
        &mut event_edge,
        "interval_secs",
        i64::try_from(cfg.interval_secs).unwrap_or(30),
    );
    set_decimal(&mut event_edge, "min_edge", cfg.min_edge);
    set_decimal(&mut event_edge, "max_entry", cfg.max_entry);
    set_integer(
        &mut event_edge,
        "shares",
        i64::try_from(cfg.shares).unwrap_or(100),
    );
    set_bool(&mut event_edge, "trade", cfg.trade);
    set_integer(
        &mut event_edge,
        "cooldown_secs",
        i64::try_from(cfg.cooldown_secs).unwrap_or(120),
    );
    set_decimal(
        &mut event_edge,
        "max_daily_spend_usd",
        cfg.max_daily_spend_usd,
    );
    if let Some(model) = cfg
        .model
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
    {
        set_string(&mut event_edge, "model", model.to_string());
    }
    set_integer(
        &mut event_edge,
        "claude_max_turns",
        i64::from(cfg.claude_max_turns),
    );

    root.insert("strategy".to_string(), toml::Value::Table(strategy));
    root.insert("event_edge".to_string(), toml::Value::Table(event_edge));

    Ok(format!(
        "# Auto-generated by platform bootstrap — event edge\n{}",
        toml::to_string(&toml::Value::Table(root))
            .expect("event_edge runtime config must serialize to TOML")
    ))
}

pub(crate) fn build_nba_comeback_runtime_config(
    cfg: &NbaComebackConfig,
    database_url: &str,
) -> String {
    let mut root = toml::map::Map::new();
    let mut strategy = toml::map::Map::new();
    let mut nba = toml::map::Map::new();

    set_string(&mut strategy, "name", "nba_comeback");
    set_bool(&mut strategy, "enabled", true);

    set_decimal(&mut nba, "min_edge", cfg.min_edge);
    set_decimal(&mut nba, "max_entry_price", cfg.max_entry_price);
    set_integer(&mut nba, "shares", i64::try_from(cfg.shares).unwrap_or(50));
    set_integer(
        &mut nba,
        "cooldown_secs",
        i64::try_from(cfg.cooldown_secs).unwrap_or(300),
    );
    set_decimal(&mut nba, "max_daily_spend_usd", cfg.max_daily_spend_usd);
    set_integer(&mut nba, "min_deficit", i64::from(cfg.min_deficit));
    set_integer(&mut nba, "max_deficit", i64::from(cfg.max_deficit));
    set_integer(&mut nba, "target_quarter", i64::from(cfg.target_quarter));
    set_integer(
        &mut nba,
        "espn_poll_interval_secs",
        i64::try_from(cfg.espn_poll_interval_secs).unwrap_or(30),
    );
    set_float(&mut nba, "min_comeback_rate", cfg.min_comeback_rate);
    set_string(&mut nba, "season", cfg.season.clone());
    set_string(&mut nba, "database_url", database_url.to_string());
    set_bool(&mut nba, "grok_enabled", cfg.grok_enabled);
    set_integer(
        &mut nba,
        "grok_interval_secs",
        i64::try_from(cfg.grok_interval_secs).unwrap_or(300),
    );
    set_decimal(&mut nba, "grok_min_edge", cfg.grok_min_edge);
    set_float(&mut nba, "grok_min_confidence", cfg.grok_min_confidence);
    set_integer(
        &mut nba,
        "grok_decision_cooldown_secs",
        i64::try_from(cfg.grok_decision_cooldown_secs).unwrap_or(60),
    );
    set_bool(&mut nba, "grok_fallback_enabled", cfg.grok_fallback_enabled);
    set_float(&mut nba, "min_reward_risk_ratio", cfg.min_reward_risk_ratio);
    set_float(&mut nba, "min_expected_value", cfg.min_expected_value);
    set_float(&mut nba, "kelly_fraction_cap", cfg.kelly_fraction_cap);
    set_decimal(
        &mut nba,
        "performance_daily_loss_limit_usd",
        cfg.performance_daily_loss_limit_usd,
    );
    set_integer(
        &mut nba,
        "performance_min_settled_trades",
        i64::try_from(cfg.performance_min_settled_trades).unwrap_or(10),
    );
    set_float(
        &mut nba,
        "performance_min_win_rate",
        cfg.performance_min_win_rate,
    );
    set_float(
        &mut nba,
        "performance_low_winrate_multiplier",
        cfg.performance_low_winrate_multiplier,
    );
    set_integer(
        &mut nba,
        "performance_loss_streak_threshold",
        i64::from(cfg.performance_loss_streak_threshold),
    );
    set_float(
        &mut nba,
        "performance_loss_streak_multiplier",
        cfg.performance_loss_streak_multiplier,
    );
    set_bool(&mut nba, "scaling_enabled", cfg.scaling_enabled);
    set_integer(
        &mut nba,
        "scaling_max_adds",
        i64::from(cfg.scaling_max_adds),
    );
    set_float(
        &mut nba,
        "scaling_min_price_drop_pct",
        cfg.scaling_min_price_drop_pct,
    );
    set_decimal(
        &mut nba,
        "scaling_max_game_exposure_usd",
        cfg.scaling_max_game_exposure_usd,
    );
    set_float(
        &mut nba,
        "scaling_min_comeback_retention",
        cfg.scaling_min_comeback_retention,
    );
    set_float(
        &mut nba,
        "scaling_min_time_remaining_mins",
        cfg.scaling_min_time_remaining_mins,
    );
    set_bool(&mut nba, "early_exit_enabled", cfg.early_exit_enabled);
    set_float(
        &mut nba,
        "early_exit_take_profit_pct",
        cfg.early_exit_take_profit_pct,
    );
    set_float(
        &mut nba,
        "early_exit_stop_loss_pct",
        cfg.early_exit_stop_loss_pct,
    );

    root.insert("strategy".to_string(), toml::Value::Table(strategy));
    root.insert("nba_comeback".to_string(), toml::Value::Table(nba));

    format!(
        "# Auto-generated by platform bootstrap — nba comeback\n{}",
        toml::to_string(&toml::Value::Table(root))
            .expect("nba_comeback runtime config must serialize to TOML")
    )
}

fn render_momentum_runtime_config(
    mut config: toml::Value,
    crypto_cfg: &CryptoTradingConfig,
    symbols: &[String],
) -> String {
    let root = config
        .as_table_mut()
        .expect("momentum runtime config must be a table");
    let strategy = root
        .entry("strategy")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[strategy] must be a table");
    strategy.insert(
        "name".to_string(),
        toml::Value::String("momentum".to_string()),
    );
    strategy.insert("enabled".to_string(), toml::Value::Boolean(true));
    strategy.insert(
        "mode".to_string(),
        toml::Value::String(if crypto_cfg.enable_price_exits {
            "predictive".to_string()
        } else {
            "confirmatory".to_string()
        }),
    );

    let entry = root
        .entry("entry")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[entry] must be a table");
    entry.insert(
        "symbols".to_string(),
        toml::Value::Array(symbols.iter().cloned().map(toml::Value::String).collect()),
    );
    entry.insert(
        "min_move".to_string(),
        toml::Value::Float(
            (crypto_cfg.min_window_move_pct * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(0.01),
        ),
    );
    entry.insert(
        "min_edge".to_string(),
        toml::Value::Float(
            (crypto_cfg.min_edge * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(5.0),
        ),
    );
    entry.insert(
        "cooldown_secs".to_string(),
        toml::Value::Float(crypto_cfg.entry_cooldown_secs as f64),
    );
    entry.insert(
        "require_mtf_agreement".to_string(),
        toml::Value::Boolean(crypto_cfg.require_mtf_agreement),
    );
    entry.insert(
        "directional_mode".to_string(),
        toml::Value::Boolean(matches!(
            crypto_cfg.entry_mode,
            crate::strategy::CryptoEntryMode::Directional
        )),
    );
    entry.insert(
        "directional_entry_threshold".to_string(),
        toml::Value::Float(
            (crypto_cfg.min_edge * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(5.0),
        ),
    );
    entry.insert(
        "min_confidence".to_string(),
        toml::Value::Float(crypto_cfg.min_signal_score.to_f64().unwrap_or(0.4)),
    );

    let timing = root
        .entry("timing")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[timing] must be a table");
    timing.insert(
        "min_time_remaining".to_string(),
        toml::Value::Float(crypto_cfg.min_time_remaining_secs as f64),
    );
    timing.insert(
        "max_time_remaining".to_string(),
        toml::Value::Float(crypto_cfg.max_time_remaining_secs as f64),
    );
    timing.insert(
        "cooldown_secs".to_string(),
        toml::Value::Float(crypto_cfg.entry_cooldown_secs as f64),
    );

    let risk = root
        .entry("risk")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[risk] must be a table");
    risk.insert(
        "shares".to_string(),
        toml::Value::Float(crypto_cfg.default_shares as f64),
    );
    risk.insert(
        "max_positions".to_string(),
        toml::Value::Float(crypto_cfg.risk_params.max_unhedged_positions.max(1) as f64),
    );

    let exit = root
        .entry("exit")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[exit] must be a table");
    exit.insert(
        "exit_edge_floor_pct".to_string(),
        toml::Value::Float(
            (crypto_cfg.exit_edge_floor * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(20.0),
        ),
    );
    exit.insert(
        "exit_price_band_pct".to_string(),
        toml::Value::Float(
            (crypto_cfg.exit_price_band * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(12.0),
        ),
    );

    format!(
        "# Auto-generated by platform bootstrap — momentum runtime\n{}",
        toml::to_string(&config).expect("runtime config must serialize to TOML")
    )
}

fn load_momentum_config_file(
    crypto_cfg: &CryptoTradingConfig,
    symbols: &[String],
) -> Option<String> {
    let candidates = [
        std::env::var("PLOY_MOMENTUM_CONFIG").ok(),
        Some("config/strategies/momentum.toml".to_string()),
        Some("/root/ploy/config/strategies/momentum.toml".to_string()),
        Some("/opt/ploy/config/strategies/momentum.toml".to_string()),
    ];
    for candidate in candidates.iter().flatten() {
        if let Ok(contents) = std::fs::read_to_string(candidate) {
            if let Ok(val) = toml::from_str::<toml::Value>(&contents) {
                if val.get("strategy").is_some() {
                    info!(path = %candidate, "loaded momentum config from external file");
                    return Some(render_momentum_runtime_config(val, crypto_cfg, symbols));
                }
            }
            warn!(path = %candidate, "momentum config file found but invalid TOML");
        }
    }
    None
}

pub(crate) fn build_momentum_runtime_config(crypto_cfg: &CryptoTradingConfig) -> Result<String> {
    if !matches!(
        crypto_cfg.entry_mode,
        crate::strategy::CryptoEntryMode::Directional
    ) {
        return Err(PloyError::Validation(format!(
            "momentum managed runtime only supports directional entry_mode for now; got {:?}",
            crypto_cfg.entry_mode
        )));
    }

    let mut symbols: Vec<String> = crypto_cfg
        .coins
        .iter()
        .map(|coin| format!("{}USDT", coin.trim_end_matches("USDT").to_ascii_uppercase()))
        .collect();
    symbols.sort();
    symbols.dedup();

    if symbols.is_empty() {
        return Err(PloyError::Validation(
            "momentum runtime has no recognized crypto symbols".to_string(),
        ));
    }

    if let Some(cfg) = load_momentum_config_file(crypto_cfg, &symbols) {
        return Ok(cfg);
    }

    let config: toml::Value =
        toml::from_str(include_str!("../../../config/strategies/momentum.toml"))
            .expect("embedded momentum runtime config must stay valid TOML");
    Ok(render_momentum_runtime_config(config, crypto_cfg, &symbols))
}

fn render_pm_5m_directional_runtime_config(mut config: toml::Value, symbols: &[String]) -> String {
    let root = config
        .as_table_mut()
        .expect("pm_5m_directional runtime config must be a table");
    let strategy = root
        .entry("strategy")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[strategy] must be a table");
    strategy.insert(
        "name".to_string(),
        toml::Value::String("pm_5m_directional".to_string()),
    );
    strategy.insert("enabled".to_string(), toml::Value::Boolean(true));

    let pm = root
        .entry("pm_5m_directional")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[pm_5m_directional] must be a table");
    set_string_array(pm, "symbols", symbols);

    format!(
        "# Auto-generated by platform bootstrap — pm 5m directional runtime\n{}",
        toml::to_string(&config).expect("runtime config must serialize to TOML")
    )
}

fn load_pm_5m_directional_config_file(symbols: &[String]) -> Option<String> {
    let candidates = [
        std::env::var("PLOY_PM_5M_DIRECTIONAL_CONFIG").ok(),
        Some("config/strategies/pm_5m_directional_default.toml".to_string()),
        Some("/root/ploy/config/strategies/pm_5m_directional_default.toml".to_string()),
        Some("/opt/ploy/config/strategies/pm_5m_directional_default.toml".to_string()),
    ];
    for candidate in candidates.iter().flatten() {
        if let Ok(contents) = std::fs::read_to_string(candidate) {
            if let Ok(val) = toml::from_str::<toml::Value>(&contents) {
                if val.get("strategy").is_some() {
                    info!(
                        path = %candidate,
                        "loaded pm_5m_directional config from external file"
                    );
                    return Some(render_pm_5m_directional_runtime_config(val, symbols));
                }
            }
            warn!(
                path = %candidate,
                "pm_5m_directional config file found but invalid TOML"
            );
        }
    }
    None
}

pub(crate) fn build_pm_5m_directional_runtime_config(coins: &[String]) -> Result<String> {
    let symbols = normalize_runtime_symbols(coins);
    if symbols.is_empty() {
        return Err(PloyError::Validation(
            "pm_5m_directional runtime has no recognized crypto symbols".to_string(),
        ));
    }

    if let Some(cfg) = load_pm_5m_directional_config_file(&symbols) {
        return Ok(cfg);
    }

    let config: toml::Value = toml::from_str(include_str!(
        "../../../config/strategies/pm_5m_directional_default.toml"
    ))
    .expect("embedded pm_5m_directional runtime config must stay valid TOML");
    Ok(render_pm_5m_directional_runtime_config(config, &symbols))
}

fn render_split_arb_runtime_config(
    mut config: toml::Value,
    symbols: &[String],
    series_ids: &[String],
) -> String {
    let root = config
        .as_table_mut()
        .expect("staggered_arb runtime config must be a table");
    let strategy = root
        .entry("strategy")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[strategy] must be a table");
    strategy.insert("enabled".to_string(), toml::Value::Boolean(true));

    let entry = root
        .entry("entry")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[entry] must be a table");
    entry.insert(
        "symbols".to_string(),
        toml::Value::Array(symbols.iter().cloned().map(toml::Value::String).collect()),
    );

    let markets = root
        .entry("markets")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[markets] must be a table");
    markets.insert(
        "series_ids".to_string(),
        toml::Value::Array(
            series_ids
                .iter()
                .cloned()
                .map(toml::Value::String)
                .collect(),
        ),
    );

    format!(
        "# Auto-generated by platform bootstrap — staggered arb (時間差套利)\n{}",
        toml::to_string(&config).expect("runtime config must serialize to TOML")
    )
}

fn load_split_arb_config_file(symbols: &[String], series_ids: &[String]) -> Option<String> {
    let candidates = [
        std::env::var("PLOY_STAGGERED_ARB_CONFIG").ok(),
        Some("config/strategies/staggered_arb.toml".to_string()),
        Some("/root/ploy/config/strategies/staggered_arb.toml".to_string()),
        Some("/opt/ploy/config/strategies/staggered_arb.toml".to_string()),
    ];
    for candidate in candidates.iter().flatten() {
        if let Ok(contents) = std::fs::read_to_string(candidate) {
            if let Ok(val) = toml::from_str::<toml::Value>(&contents) {
                if val.get("strategy").is_some() {
                    info!(
                        path = %candidate,
                        "loaded staggered_arb config from external file"
                    );
                    return Some(render_split_arb_runtime_config(val, symbols, series_ids));
                }
            }
            warn!(path = %candidate, "staggered_arb config file found but invalid TOML");
        }
    }
    None
}

pub(crate) fn build_split_arb_runtime_config(symbols: &[String], series_ids: &[String]) -> String {
    if let Some(cfg) = load_split_arb_config_file(symbols, series_ids) {
        return cfg;
    }

    let config: toml::Value = toml::from_str(include_str!(
        "../../../config/strategies/staggered_arb.toml"
    ))
    .expect("embedded staggered_arb runtime config must stay valid TOML");
    render_split_arb_runtime_config(config, symbols, series_ids)
}

#[cfg(test)]
mod tests {
    use super::build_pm_5m_directional_runtime_config;

    #[test]
    fn build_pm_5m_directional_runtime_config_sets_strategy_and_symbols() {
        let config =
            build_pm_5m_directional_runtime_config(&["ethusdt".to_string(), "btc".to_string()])
                .expect("pm5 runtime config");
        let value: toml::Value = toml::from_str(&config).expect("valid toml");

        assert_eq!(
            value
                .get("strategy")
                .and_then(|table| table.get("name"))
                .and_then(|name| name.as_str()),
            Some("pm_5m_directional")
        );
        assert_eq!(
            value
                .get("strategy")
                .and_then(|table| table.get("enabled"))
                .and_then(|enabled| enabled.as_bool()),
            Some(true)
        );

        let symbols = value
            .get("pm_5m_directional")
            .and_then(|table| table.get("symbols"))
            .and_then(|symbols| symbols.as_array())
            .expect("symbols array")
            .iter()
            .filter_map(|value| value.as_str())
            .collect::<Vec<_>>();
        assert_eq!(symbols, vec!["BTCUSDT", "ETHUSDT"]);
    }
}
