use rust_decimal::prelude::ToPrimitive;

use crate::config::{EventEdgeAgentConfig, NbaComebackConfig};
use crate::error::{PloyError, Result};

use super::deployment_matrix::{coin_symbol_for, crypto_series_id_for};
mod crypto_managed_configs;
mod crypto_templates;
pub(crate) use crypto_managed_configs::build_crypto_lob_ml_runtime_config;
#[cfg(feature = "rl")]
pub(crate) use crypto_managed_configs::build_crypto_rl_policy_runtime_config;
pub(crate) use crypto_templates::{
    build_momentum_runtime_config, build_split_arb_runtime_config,
};

fn set_integer(table: &mut toml::map::Map<String, toml::Value>, key: &str, value: i64) {
    table.insert(key.to_string(), toml::Value::Integer(value));
}

fn set_float(table: &mut toml::map::Map<String, toml::Value>, key: &str, value: f64) {
    table.insert(key.to_string(), toml::Value::Float(value));
}

fn set_decimal(
    table: &mut toml::map::Map<String, toml::Value>,
    key: &str,
    value: rust_decimal::Decimal,
) {
    set_float(table, key, value.to_f64().unwrap_or(0.0));
}

fn set_bool(table: &mut toml::map::Map<String, toml::Value>, key: &str, value: bool) {
    table.insert(key.to_string(), toml::Value::Boolean(value));
}

fn set_string(
    table: &mut toml::map::Map<String, toml::Value>,
    key: &str,
    value: impl Into<String>,
) {
    table.insert(key.to_string(), toml::Value::String(value.into()));
}

fn set_string_array(table: &mut toml::map::Map<String, toml::Value>, key: &str, values: &[String]) {
    table.insert(
        key.to_string(),
        toml::Value::Array(values.iter().cloned().map(toml::Value::String).collect()),
    );
}

pub(crate) fn build_pattern_memory_runtime_config(coins: &[String]) -> Result<String> {
    let mut selected: Vec<String> = coins
        .iter()
        .filter_map(|c| {
            c.strip_suffix("USDT")
                .map(|s| s.to_string())
                .or_else(|| Some(c.clone()))
        })
        .map(|c| c.to_ascii_uppercase())
        .collect();
    selected.sort();
    selected.dedup();

    let mut markets_block = String::new();
    for coin in selected {
        if let (Some(symbol), Some(series_id)) =
            (coin_symbol_for(&coin), crypto_series_id_for(&coin, "5m"))
        {
            markets_block.push_str("\n[[markets]]\n");
            markets_block.push_str(&format!("symbol = \"{symbol}\"\n"));
            markets_block.push_str(&format!("series_id = \"{series_id}\"\n"));
        }
    }

    if markets_block.trim().is_empty() {
        return Err(PloyError::Validation(
            "pattern_memory runtime has no recognized crypto coins/series ids".to_string(),
        ));
    }

    Ok(format!(
        r#"# Auto-generated by platform bootstrap
[strategy]
name = "pattern_memory"
enabled = true
{markets}
[pattern]
corr_threshold = 0.70
alpha = 1.0
beta = 1.0
min_matches = 3
min_n_eff = 2.0
min_confidence = 0.60

[filter_15m]
enabled = true
min_confidence = 0.55
min_n_eff = 1.0

[timing]
target_remaining_secs = 300
tolerance_secs = 45
min_remaining_secs = 60

[trade]
shares = 100
max_entry_price = 0.55
min_net_ev = 0.0
cooldown_secs = 30
"#,
        markets = markets_block
    ))
}

pub(crate) fn build_event_edge_runtime_config(cfg: &EventEdgeAgentConfig) -> Result<String> {
    if cfg.event_ids.is_empty() && cfg.titles.is_empty() {
        return Err(PloyError::Validation(
            "event_edge runtime requires at least one event_id or title target".to_string(),
        ));
    }

    let mut root = toml::map::Map::new();
    let mut strategy = toml::map::Map::new();
    let mut event_edge = toml::map::Map::new();

    set_string(&mut strategy, "name", "event_edge");
    set_bool(&mut strategy, "enabled", true);

    set_string(&mut event_edge, "framework", cfg.framework.clone());
    set_string_array(&mut event_edge, "event_ids", &cfg.event_ids);
    set_string_array(&mut event_edge, "titles", &cfg.titles);
    set_integer(
        &mut event_edge,
        "interval_secs",
        i64::try_from(cfg.interval_secs).unwrap_or(30),
    );
    set_decimal(&mut event_edge, "min_edge", cfg.min_edge);
    set_decimal(&mut event_edge, "max_entry", cfg.max_entry);
    set_integer(
        &mut event_edge,
        "shares",
        i64::try_from(cfg.shares).unwrap_or(100),
    );
    set_bool(&mut event_edge, "trade", cfg.trade);
    set_integer(
        &mut event_edge,
        "cooldown_secs",
        i64::try_from(cfg.cooldown_secs).unwrap_or(120),
    );
    set_decimal(
        &mut event_edge,
        "max_daily_spend_usd",
        cfg.max_daily_spend_usd,
    );
    if let Some(model) = cfg
        .model
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
    {
        set_string(&mut event_edge, "model", model.to_string());
    }
    set_integer(
        &mut event_edge,
        "claude_max_turns",
        i64::from(cfg.claude_max_turns),
    );

    root.insert("strategy".to_string(), toml::Value::Table(strategy));
    root.insert("event_edge".to_string(), toml::Value::Table(event_edge));

    Ok(format!(
        "# Auto-generated by platform bootstrap — event edge\n{}",
        toml::to_string(&toml::Value::Table(root))
            .expect("event_edge runtime config must serialize to TOML")
    ))
}

pub(crate) fn build_nba_comeback_runtime_config(
    cfg: &NbaComebackConfig,
    database_url: &str,
) -> String {
    let mut root = toml::map::Map::new();
    let mut strategy = toml::map::Map::new();
    let mut nba = toml::map::Map::new();

    set_string(&mut strategy, "name", "nba_comeback");
    set_bool(&mut strategy, "enabled", true);

    set_decimal(&mut nba, "min_edge", cfg.min_edge);
    set_decimal(&mut nba, "max_entry_price", cfg.max_entry_price);
    set_integer(&mut nba, "shares", i64::try_from(cfg.shares).unwrap_or(50));
    set_integer(
        &mut nba,
        "cooldown_secs",
        i64::try_from(cfg.cooldown_secs).unwrap_or(300),
    );
    set_decimal(&mut nba, "max_daily_spend_usd", cfg.max_daily_spend_usd);
    set_integer(&mut nba, "min_deficit", i64::from(cfg.min_deficit));
    set_integer(&mut nba, "max_deficit", i64::from(cfg.max_deficit));
    set_integer(&mut nba, "target_quarter", i64::from(cfg.target_quarter));
    set_integer(
        &mut nba,
        "espn_poll_interval_secs",
        i64::try_from(cfg.espn_poll_interval_secs).unwrap_or(30),
    );
    set_float(&mut nba, "min_comeback_rate", cfg.min_comeback_rate);
    set_string(&mut nba, "season", cfg.season.clone());
    set_string(&mut nba, "database_url", database_url.to_string());
    set_bool(&mut nba, "grok_enabled", cfg.grok_enabled);
    set_integer(
        &mut nba,
        "grok_interval_secs",
        i64::try_from(cfg.grok_interval_secs).unwrap_or(300),
    );
    set_decimal(&mut nba, "grok_min_edge", cfg.grok_min_edge);
    set_float(&mut nba, "grok_min_confidence", cfg.grok_min_confidence);
    set_integer(
        &mut nba,
        "grok_decision_cooldown_secs",
        i64::try_from(cfg.grok_decision_cooldown_secs).unwrap_or(60),
    );
    set_bool(&mut nba, "grok_fallback_enabled", cfg.grok_fallback_enabled);
    set_float(&mut nba, "min_reward_risk_ratio", cfg.min_reward_risk_ratio);
    set_float(&mut nba, "min_expected_value", cfg.min_expected_value);
    set_float(&mut nba, "kelly_fraction_cap", cfg.kelly_fraction_cap);
    set_decimal(
        &mut nba,
        "performance_daily_loss_limit_usd",
        cfg.performance_daily_loss_limit_usd,
    );
    set_integer(
        &mut nba,
        "performance_min_settled_trades",
        i64::try_from(cfg.performance_min_settled_trades).unwrap_or(10),
    );
    set_float(
        &mut nba,
        "performance_min_win_rate",
        cfg.performance_min_win_rate,
    );
    set_float(
        &mut nba,
        "performance_low_winrate_multiplier",
        cfg.performance_low_winrate_multiplier,
    );
    set_integer(
        &mut nba,
        "performance_loss_streak_threshold",
        i64::from(cfg.performance_loss_streak_threshold),
    );
    set_float(
        &mut nba,
        "performance_loss_streak_multiplier",
        cfg.performance_loss_streak_multiplier,
    );
    set_bool(&mut nba, "scaling_enabled", cfg.scaling_enabled);
    set_integer(
        &mut nba,
        "scaling_max_adds",
        i64::from(cfg.scaling_max_adds),
    );
    set_float(
        &mut nba,
        "scaling_min_price_drop_pct",
        cfg.scaling_min_price_drop_pct,
    );
    set_decimal(
        &mut nba,
        "scaling_max_game_exposure_usd",
        cfg.scaling_max_game_exposure_usd,
    );
    set_float(
        &mut nba,
        "scaling_min_comeback_retention",
        cfg.scaling_min_comeback_retention,
    );
    set_float(
        &mut nba,
        "scaling_min_time_remaining_mins",
        cfg.scaling_min_time_remaining_mins,
    );
    set_bool(&mut nba, "early_exit_enabled", cfg.early_exit_enabled);
    set_float(
        &mut nba,
        "early_exit_take_profit_pct",
        cfg.early_exit_take_profit_pct,
    );
    set_float(
        &mut nba,
        "early_exit_stop_loss_pct",
        cfg.early_exit_stop_loss_pct,
    );

    root.insert("strategy".to_string(), toml::Value::Table(strategy));
    root.insert("nba_comeback".to_string(), toml::Value::Table(nba));

    format!(
        "# Auto-generated by platform bootstrap — nba comeback\n{}",
        toml::to_string(&toml::Value::Table(root))
            .expect("nba_comeback runtime config must serialize to TOML")
    )
}
