use rust_decimal::prelude::ToPrimitive;
use tracing::{info, warn};

use crate::error::{PloyError, Result};
use crate::strategy::CryptoTradingConfig;

fn render_momentum_runtime_config(
    mut config: toml::Value,
    crypto_cfg: &CryptoTradingConfig,
    symbols: &[String],
) -> String {
    let root = config
        .as_table_mut()
        .expect("momentum runtime config must be a table");
    let strategy = root
        .entry("strategy")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[strategy] must be a table");
    strategy.insert(
        "name".to_string(),
        toml::Value::String("momentum".to_string()),
    );
    strategy.insert("enabled".to_string(), toml::Value::Boolean(true));
    strategy.insert(
        "mode".to_string(),
        toml::Value::String(if crypto_cfg.enable_price_exits {
            "predictive".to_string()
        } else {
            "confirmatory".to_string()
        }),
    );

    let entry = root
        .entry("entry")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[entry] must be a table");
    entry.insert(
        "symbols".to_string(),
        toml::Value::Array(symbols.iter().cloned().map(toml::Value::String).collect()),
    );
    entry.insert(
        "min_move".to_string(),
        toml::Value::Float(
            (crypto_cfg.min_window_move_pct * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(0.01),
        ),
    );
    entry.insert(
        "min_edge".to_string(),
        toml::Value::Float(
            (crypto_cfg.min_edge * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(5.0),
        ),
    );
    entry.insert(
        "cooldown_secs".to_string(),
        toml::Value::Float(crypto_cfg.entry_cooldown_secs as f64),
    );
    entry.insert(
        "require_mtf_agreement".to_string(),
        toml::Value::Boolean(crypto_cfg.require_mtf_agreement),
    );
    entry.insert(
        "directional_mode".to_string(),
        toml::Value::Boolean(matches!(
            crypto_cfg.entry_mode,
            crate::strategy::CryptoEntryMode::Directional
        )),
    );
    entry.insert(
        "directional_entry_threshold".to_string(),
        toml::Value::Float(
            (crypto_cfg.min_edge * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(5.0),
        ),
    );
    entry.insert(
        "min_confidence".to_string(),
        toml::Value::Float(crypto_cfg.min_signal_score.to_f64().unwrap_or(0.4)),
    );

    let timing = root
        .entry("timing")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[timing] must be a table");
    timing.insert(
        "min_time_remaining".to_string(),
        toml::Value::Float(crypto_cfg.min_time_remaining_secs as f64),
    );
    timing.insert(
        "max_time_remaining".to_string(),
        toml::Value::Float(crypto_cfg.max_time_remaining_secs as f64),
    );
    timing.insert(
        "cooldown_secs".to_string(),
        toml::Value::Float(crypto_cfg.entry_cooldown_secs as f64),
    );

    let risk = root
        .entry("risk")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[risk] must be a table");
    risk.insert(
        "shares".to_string(),
        toml::Value::Float(crypto_cfg.default_shares as f64),
    );
    risk.insert(
        "max_positions".to_string(),
        toml::Value::Float(crypto_cfg.risk_params.max_unhedged_positions.max(1) as f64),
    );

    let exit = root
        .entry("exit")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[exit] must be a table");
    exit.insert(
        "exit_edge_floor_pct".to_string(),
        toml::Value::Float(
            (crypto_cfg.exit_edge_floor * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(20.0),
        ),
    );
    exit.insert(
        "exit_price_band_pct".to_string(),
        toml::Value::Float(
            (crypto_cfg.exit_price_band * rust_decimal_macros::dec!(100))
                .to_f64()
                .unwrap_or(12.0),
        ),
    );

    format!(
        "# Auto-generated by platform bootstrap — momentum runtime\n{}",
        toml::to_string(&config).expect("runtime config must serialize to TOML")
    )
}

fn load_momentum_config_file(
    crypto_cfg: &CryptoTradingConfig,
    symbols: &[String],
) -> Option<String> {
    let candidates = [
        std::env::var("PLOY_MOMENTUM_CONFIG").ok(),
        Some("config/strategies/momentum.toml".to_string()),
        Some("/root/ploy/config/strategies/momentum.toml".to_string()),
        Some("/opt/ploy/config/strategies/momentum.toml".to_string()),
    ];
    for candidate in candidates.iter().flatten() {
        if let Ok(contents) = std::fs::read_to_string(candidate) {
            if let Ok(val) = toml::from_str::<toml::Value>(&contents) {
                if val.get("strategy").is_some() {
                    info!(path = %candidate, "loaded momentum config from external file");
                    return Some(render_momentum_runtime_config(val, crypto_cfg, symbols));
                }
            }
            warn!(path = %candidate, "momentum config file found but invalid TOML");
        }
    }
    None
}

pub(crate) fn build_momentum_runtime_config(crypto_cfg: &CryptoTradingConfig) -> Result<String> {
    if !matches!(
        crypto_cfg.entry_mode,
        crate::strategy::CryptoEntryMode::Directional
    ) {
        return Err(PloyError::Validation(format!(
            "momentum managed runtime only supports directional entry_mode for now; got {:?}",
            crypto_cfg.entry_mode
        )));
    }

    let mut symbols: Vec<String> = crypto_cfg
        .coins
        .iter()
        .map(|coin| format!("{}USDT", coin.trim_end_matches("USDT").to_ascii_uppercase()))
        .collect();
    symbols.sort();
    symbols.dedup();

    if symbols.is_empty() {
        return Err(PloyError::Validation(
            "momentum runtime has no recognized crypto symbols".to_string(),
        ));
    }

    if let Some(cfg) = load_momentum_config_file(crypto_cfg, &symbols) {
        return Ok(cfg);
    }

    let config: toml::Value =
        toml::from_str(include_str!("../../../../config/strategies/momentum.toml"))
            .expect("embedded momentum runtime config must stay valid TOML");
    Ok(render_momentum_runtime_config(config, crypto_cfg, &symbols))
}

fn render_split_arb_runtime_config(
    mut config: toml::Value,
    symbols: &[String],
    series_ids: &[String],
) -> String {
    let root = config
        .as_table_mut()
        .expect("staggered_arb runtime config must be a table");
    let strategy = root
        .entry("strategy")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[strategy] must be a table");
    strategy.insert("enabled".to_string(), toml::Value::Boolean(true));

    let entry = root
        .entry("entry")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[entry] must be a table");
    entry.insert(
        "symbols".to_string(),
        toml::Value::Array(symbols.iter().cloned().map(toml::Value::String).collect()),
    );

    let markets = root
        .entry("markets")
        .or_insert_with(|| toml::Value::Table(Default::default()))
        .as_table_mut()
        .expect("[markets] must be a table");
    markets.insert(
        "series_ids".to_string(),
        toml::Value::Array(
            series_ids
                .iter()
                .cloned()
                .map(toml::Value::String)
                .collect(),
        ),
    );

    format!(
        "# Auto-generated by platform bootstrap — staggered arb (時間差套利)\n{}",
        toml::to_string(&config).expect("runtime config must serialize to TOML")
    )
}

fn load_split_arb_config_file(symbols: &[String], series_ids: &[String]) -> Option<String> {
    let candidates = [
        std::env::var("PLOY_STAGGERED_ARB_CONFIG").ok(),
        Some("config/strategies/staggered_arb.toml".to_string()),
        Some("/root/ploy/config/strategies/staggered_arb.toml".to_string()),
        Some("/opt/ploy/config/strategies/staggered_arb.toml".to_string()),
    ];
    for candidate in candidates.iter().flatten() {
        if let Ok(contents) = std::fs::read_to_string(candidate) {
            if let Ok(val) = toml::from_str::<toml::Value>(&contents) {
                if val.get("strategy").is_some() {
                    info!(
                        path = %candidate,
                        "loaded staggered_arb config from external file"
                    );
                    return Some(render_split_arb_runtime_config(val, symbols, series_ids));
                }
            }
            warn!(path = %candidate, "staggered_arb config file found but invalid TOML");
        }
    }
    None
}

pub(crate) fn build_split_arb_runtime_config(symbols: &[String], series_ids: &[String]) -> String {
    if let Some(cfg) = load_split_arb_config_file(symbols, series_ids) {
        return cfg;
    }

    let config: toml::Value = toml::from_str(include_str!(
        "../../../../config/strategies/staggered_arb.toml"
    ))
    .expect("embedded staggered_arb runtime config must stay valid TOML");
    render_split_arb_runtime_config(config, symbols, series_ids)
}
