#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const repoRoot = path.resolve(import.meta.dirname, "..");
const schemaDir = path.join(repoRoot, "contracts", "schemas");
const targets = [
  path.join(repoRoot, "ploy-frontend", "src", "types", "operator-contracts.ts"),
  path.join(repoRoot, "ploy-sidecar", "src", "contracts", "operator-contracts.ts"),
];
const schemaFiles = [
  "deployment-summary.schema.json",
  "deployment-apply-request.schema.json",
  "deployment-control-request.schema.json",
  "paper-intent-request.schema.json",
  "paper-intent-response.schema.json",
  "trading-state-snapshot.schema.json",
  "dry-run-performance-report.schema.json",
  "system-status.schema.json",
  "system-control-response.schema.json",
  "audit-log-entry.schema.json",
  "control-plane-error-response.schema.json",
  "operator-event.schema.json",
  "agent-run-record.schema.json",
  "agent-run-create-request.schema.json",
  "agent-run-create-response.schema.json",
];

const check = process.argv.includes("--check");
const emitted = new Set();
const lines = [
  "// @generated by scripts/export_operator_contract_types.mjs",
  "// Source of truth: contracts/schemas/*.schema.json",
  "",
  "export type JsonValue =",
  "  | string",
  "  | number",
  "  | boolean",
  "  | null",
  "  | JsonValue[]",
  "  | { [key: string]: JsonValue };",
  "",
];

function readSchema(fileName) {
  return JSON.parse(fs.readFileSync(path.join(schemaDir, fileName), "utf8"));
}

function refName(ref) {
  return ref.slice(ref.lastIndexOf("/") + 1);
}

function quote(value) {
  return JSON.stringify(value);
}

function tsName(name) {
  return name.replace(/[^A-Za-z0-9_$]/g, "_");
}

function schemaToTs(schema) {
  if (!schema || schema === true) return "JsonValue";
  if (schema.$ref) return tsName(refName(schema.$ref));
  if (schema.allOf?.length === 1) return schemaToTs(schema.allOf[0]);
  if (schema.oneOf) return schema.oneOf.map(schemaToTs).join(" | ");
  if (schema.anyOf) return schema.anyOf.map(schemaToTs).join(" | ");
  if (schema.enum) return schema.enum.map(quote).join(" | ");

  const type = schema.type;
  if (Array.isArray(type)) {
    return type.map((part) => schemaToTs({ ...schema, type: part })).join(" | ");
  }
  if (type === "array") return `${schemaToTs(schema.items)}[]`;
  if (type === "integer" || type === "number") return "number";
  if (type === "boolean") return "boolean";
  if (type === "null") return "null";
  if (type === "string") return "string";
  if (type === "object" || schema.properties) return inlineObject(schema);
  return "JsonValue";
}

function inlineObject(schema) {
  const required = new Set(schema.required ?? []);
  const props = schema.properties ?? {};
  const entries = Object.entries(props).map(([name, child]) => {
    const optional = required.has(name) ? "" : "?";
    return `${name}${optional}: ${schemaToTs(child)};`;
  });
  if (entries.length === 0) return "{ [key: string]: JsonValue }";
  return `{ ${entries.join(" ")} }`;
}

function emitDefinition(name, schema) {
  const cleanName = tsName(name);
  if (emitted.has(cleanName)) return;
  emitted.add(cleanName);

  for (const [definitionName, definitionSchema] of Object.entries(schema.definitions ?? {})) {
    emitDefinition(definitionName, definitionSchema);
  }

  if (schema.enum) {
    lines.push(`export type ${cleanName} = ${schemaToTs(schema)};`, "");
    return;
  }

  if (schema.type === "object" || schema.properties) {
    lines.push(`export interface ${cleanName} ${inlineObject(schema)}`, "");
    return;
  }

  lines.push(`export type ${cleanName} = ${schemaToTs(schema)};`, "");
}

for (const fileName of schemaFiles) {
  const schema = readSchema(fileName);
  emitDefinition(schema.title, schema);
}

const output = `${lines.join("\n").replace(/[ \t]+$/gm, "").trimEnd()}\n`;
const stale = [];

for (const target of targets) {
  if (check) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
    if (current !== output) stale.push(path.relative(repoRoot, target));
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, output);
    console.log(`wrote ${path.relative(repoRoot, target)}`);
  }
}

if (stale.length > 0) {
  console.error(`stale generated operator contract types: ${stale.join(", ")}`);
  process.exit(1);
}
