// @generated by scripts/export_operator_contract_types.mjs
// Source of truth: contracts/schemas/*.schema.json

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export type DeploymentRuntimeMode = "paper" | "live";

export type DeploymentState = "enabled" | "draining" | "disabled" | "archived";

export type DesiredState = "running" | "paused" | "stopped";

export type ObservedState = "starting" | "running" | "degraded" | "paused" | "stopped" | "failed";

export interface DeploymentSummary { account_id?: string; deployment_id: string; deployment_state?: DeploymentState; desired_state: DesiredState; max_gross_exposure?: string | null; observed_state: ObservedState; runtime_mode?: DeploymentRuntimeMode; }

export interface DeploymentApplyRequest { account_id?: string; bundle_id: string; deployment_id: string; deployment_state?: DeploymentState; desired_state: DesiredState; max_gross_exposure?: string | null; runtime_mode: DeploymentRuntimeMode; }

export interface DeploymentControlRequest { deployment_state?: DeploymentState | null; desired_state?: DesiredState | null; }

export type IntentPurpose = "entry" | "exit" | "reduce" | "hedge" | "cancel";

export interface PaperIntentRequest { idempotency_key?: string | null; limit_price?: string | null; market_id: string; purpose: IntentPurpose; quantity: string; side: string; token_id: string; }

export interface PaperIntentResponse { deployment_id: string; intent_id: string; last_error?: string | null; order_id: string; rejection_reason?: string | null; state: string; venue_order_id?: string | null; }

export interface FillSnapshot { fee: string; fill_id: string; order_id: string; price: string; quantity: string; side: string; timestamp: string; token_id: string; }

export interface OrderSnapshot { filled_qty: string; idempotency_key?: string | null; intent_id: string; last_error?: string | null; limit_price?: string | null; order_id: string; rejection_reason?: string | null; requested_qty: string; revision?: number; state: string; state_changed_at?: string | null; token_id: string; venue_order_history?: string[]; venue_order_id?: string | null; }

export interface PnlSnapshotResponse { net_pnl: string; realized_pnl: string; total_fees: string; unrealized_pnl: string; }

export interface PositionSnapshotResponse { avg_entry_price: string; net_qty: string; realized_pnl: string; token_id: string; }

export interface RiskSnapshotResponse { active_orders: number; gross_exposure: string; open_positions: number; pending_intents: number; reserved_order_exposure: string; total_gross_exposure: string; }

export interface TradingIntentSnapshot { created_at: string; intent_id: string; limit_price?: string | null; market_id: string; purpose: IntentPurpose; quantity: string; side: string; token_id: string; }

export interface TradingStateSnapshot { deployment_id: string; fills: FillSnapshot[]; intents: TradingIntentSnapshot[]; orders: OrderSnapshot[]; pnl: PnlSnapshotResponse; positions: PositionSnapshotResponse[]; risk: RiskSnapshotResponse; runtime_mode: DeploymentRuntimeMode; }

export interface DryRunClosedTradeRow { closed_at?: string | null; deployment_id?: string | null; entry_price?: number | null; entry_time_remaining_secs?: number | null; event_id?: string | null; exit_price?: number | null; exit_type: string; experiment_label?: string | null; market_side?: string | null; net_pnl: number; notional: number; opened_at?: string | null; quantity: number; runtime_mode?: string | null; strategy_id?: string | null; symbol?: string | null; trade_key?: string | null; window_label: string; window_secs?: number | null; }

export interface DryRunDailyRow { closed_trade_count: number; confirmed_pnl: number; confirmed_trade_count: number; fees: number; losses: number; net_pnl: number; open_quantity: number; trade_count: number; trading_day_cst?: string | null; wins: number; }

export interface DryRunDailyWindowRow { closed_trade_count: number; losses: number; net_pnl: number; trade_count: number; trading_day_cst: string; window_label: string; window_secs?: number | null; wins: number; }

export interface DryRunEquityPoint { cumulative: number; drawdown: number; index: number; label: string; pnl: number; symbol?: string | null; timestamp?: string | null; }

export interface DryRunExecutionDiagnostics { basis: string; partial_buy_threshold_pct: number; strategies: JsonValue[]; summary: { [key: string]: JsonValue }; }

export interface DryRunHourlyRow { closed_trade_count: number; cumulative_pnl: number; drawdown: number; losses: number; net_pnl: number; trade_count: number; trading_hour_cst: string; wins: number; }

export interface DryRunHourlyWindowRow { closed_trade_count: number; losses: number; net_pnl: number; trade_count: number; trading_hour_cst: string; window_label: string; window_secs?: number | null; wins: number; }

export interface DryRunMetrics { avg_trade?: number | null; closed_trade_count_for_sharpe?: number | null; daily_sharpe_basis?: string | null; equity_points: number; gross_loss: number; gross_profit: number; max_drawdown: number; profit_factor?: NumberOrText | null; sharpe?: number | null; sharpe_basis?: string | null; sharpe_daily_ann?: number | null; sharpe_per_trade?: number | null; }

export interface DryRunOpenPositionRow { deployment_id?: string | null; entry_price?: number | null; entry_time_remaining_secs?: number | null; event_id?: string | null; experiment_label?: string | null; market_side?: string | null; notional: number; opened_at?: string | null; quantity: number; runtime_mode?: string | null; strategy_id?: string | null; symbol?: string | null; trade_key?: string | null; window_label: string; window_secs?: number | null; }

export interface DryRunPairingReport { current_view_rows: number; fills_in_mixed_event_groups: number; mixed_event_groups: number; pair_key: string; side_aware_rows: number; }

export interface DryRunRuntimeEvidence { basis: string; events?: JsonValue[]; fills?: JsonValue[]; orders?: JsonValue[]; schema_version: number; }

export interface DryRunStrategyReport { by_window: DryRunWindowRow[]; closed_trades: DryRunClosedTradeRow[]; daily: DryRunDailyRow[]; daily_by_window: DryRunDailyWindowRow[]; deployment_id: string; equity_curve: DryRunEquityPoint[]; execution_diagnostics?: DryRunExecutionDiagnostics | null; experiment_label?: string | null; hourly?: DryRunHourlyRow[]; hourly_by_window?: DryRunHourlyWindowRow[]; label: string; metrics: DryRunMetrics; open_positions: DryRunOpenPositionRow[]; recent_closed: DryRunClosedTradeRow[]; runtime_mode: string; strategy_id: string; summary: DryRunSummary; symbols: DryRunSymbolRow[]; symbols_by_window: DryRunSymbolRow[]; }

export interface DryRunSummary { closed_trades: number; latest_closed_at?: string | null; latest_opened_at?: string | null; losses: number; open_exposure: number; open_positions: number; realized_pnl: number; total_fees: number; total_trades: number; win_rate_pct: number; wins: number; }

export interface DryRunSymbolRow { avg_entry?: number | null; losses: number; net_pnl: number; symbol: string; trades: number; window_label?: string | null; window_secs?: number | null; wins: number; }

export interface DryRunWindowRow { avg_entry?: number | null; avg_pnl?: number | null; closed_trades: number; losses: number; max_entry_ttr_secs?: number | null; min_entry_ttr_secs?: number | null; realized_pnl: number; total_trades: number; win_rate_pct: number; window_label: string; window_secs?: number | null; wins: number; }

export type NumberOrText = number | string;

export interface DryRunPerformanceReport { by_window: DryRunWindowRow[]; closed_trades: DryRunClosedTradeRow[]; daily: DryRunDailyRow[]; daily_by_window: DryRunDailyWindowRow[]; equity_curve: DryRunEquityPoint[]; execution_diagnostics?: DryRunExecutionDiagnostics | null; generated_at: string; hourly?: DryRunHourlyRow[]; hourly_by_window?: DryRunHourlyWindowRow[]; metrics: DryRunMetrics; open_positions: DryRunOpenPositionRow[]; pairing: DryRunPairingReport; recent_closed: DryRunClosedTradeRow[]; runtime_evidence?: DryRunRuntimeEvidence | null; strategies: DryRunStrategyReport[]; summary: DryRunSummary; symbols: DryRunSymbolRow[]; symbols_by_window: DryRunSymbolRow[]; }

export interface SystemStatus { active_alert_count?: number; database_connected: boolean; error_count_1h: number; last_live_reconcile_error?: string | null; last_live_reconcile_success_at?: string | null; last_trade_time?: string | null; live_reconcile_failures?: number; next_live_reconcile_at?: string | null; stale_source_count?: number; status: string; strategy: string; uptime_seconds: number; version: string; websocket_connected: boolean; }

export interface SystemControlResponse { message: string; success: boolean; }

export interface AuditLogEntry { auth_level: string; client_addr?: string | null; message?: string | null; method: string; outcome: string; path: string; required_access: string; status_code: number; timestamp: string; }

export interface ControlPlaneErrorResponse { error: string; message?: string | null; }

export interface ActiveAlert { alert_id: string; kind: AlertKind; message: string; severity: AlertSeverity; source_id: string; triggered_at: string; }

export type AlertKind = "source_stale";

export type AlertSeverity = "warning" | "critical";

export interface AlertSnapshotEvent { alerts: ActiveAlert[]; }

export interface DeploymentSnapshotEvent { deployments: DeploymentSummary[]; }

export type HeartbeatState = "healthy" | "stale";

export interface HeartbeatStatus { last_seen_at?: string | null; message?: string | null; source_id: string; source_kind: string; stale_after_seconds: number; state: HeartbeatState; }

export interface LogEntry { component: string; level: string; message: string; metadata?: JsonValue; timestamp: string; }

export interface MarketData { best_ask: number; best_bid: number; last_price: number; spread: number; timestamp: string; token_id: string; token_name: string; volume_24h: number; }

export interface MetricsSnapshotEvent { metrics: PlatformMetrics; }

export interface OversightRecommendedAction { kind: string; operator_command: string; target: string; }

export interface OversightReport { deployments_reviewed: number; platform_status: string; recommended_actions: OversightRecommendedAction[]; signal_count: number; signals: OversightSignal[]; timestamp: string; }

export interface OversightSignal { deployment_id?: string | null; evidence: string[]; kind: string; message: string; recommended_action: string; severity: string; }

export interface OversightSnapshotEvent { oversight: OversightReport; }

export interface PlatformMetrics { active_alerts: number; degraded_deployments: number; heartbeats: HeartbeatStatus[]; host_cpu_pressure_milli_percent?: number | null; host_load_average_1m_milli?: number | null; host_memory_available_mb?: number | null; last_live_reconcile_success_at?: string | null; last_trade_time?: string | null; live_deployments: number; live_reconcile_failures: number; process_memory_mb?: number | null; stale_sources: number; total_deployments: number; }

export interface PositionResponse { current_price: number; duration_seconds: number; entry_price: number; entry_time: string; shares: number; side: string; token_id: string; token_name: string; unrealized_pnl: number; }

export type ProposalActionKind = "pause_deployment" | "drain_deployment" | "reduce_max_exposure";

export interface ProposalSnapshotEvent { proposals: SafetyProposal[]; }

export type ProposalStatus = "pending" | "approved" | "rejected" | "failed";

export interface SafetyProposal { action_kind: ProposalActionKind; created_at: string; decided_at?: string | null; decision_note?: string | null; evidence: string[]; proposal_id: string; proposed_max_gross_exposure?: string | null; rationale: string; source_run_id?: string | null; status: ProposalStatus; target_deployment_id: string; }

export interface StatusUpdate { status: string; }

export interface SystemSnapshotEvent { system: SystemStatus; }

export interface TradeResponse { entry_price: number; error_message?: string | null; exit_price?: number | null; id: string; pnl?: number | null; shares: number; side: string; status: string; timestamp: string; token_id: string; token_name: string; }

export interface TradingSnapshotEvent { trading: TradingStateSnapshot[]; }

export type OperatorEvent = { data: LogEntry; type: "log"; } | { data: TradeResponse; type: "trade"; } | { data: PositionResponse; type: "position"; } | { data: MarketData; type: "market"; } | { data: StatusUpdate; type: "status"; } | { data: SystemSnapshotEvent; type: "system_snapshot"; } | { data: DeploymentSnapshotEvent; type: "deployment_snapshot"; } | { data: TradingSnapshotEvent; type: "trading_snapshot"; } | { data: MetricsSnapshotEvent; type: "metrics_snapshot"; } | { data: AlertSnapshotEvent; type: "alert_snapshot"; } | { data: OversightSnapshotEvent; type: "oversight_snapshot"; } | { data: ProposalSnapshotEvent; type: "proposal_snapshot"; };

export interface AgentToolCallRecord { name: string; status: string; }

export interface AgentRunRecord { cycle_kind: string; deployment_count: number; evaluation?: JsonValue; failure_reason?: string | null; finished_at?: string | null; model: string; operator_recommendations: number; output_summary?: JsonValue; oversight_alerts: number; oversight_playbook_count: number; oversight_signal_count: number; platform_status?: string | null; research_reports: number; run_id: string; runtime_context?: JsonValue; session_id?: string | null; started_at: string; status: string; tool_calls: AgentToolCallRecord[]; total_cost_usd?: number | null; }

export interface AgentRunCreateRequest { autonomy_mode: string; budget_usd: number; max_turns: number; objective: string; run_contract: string; run_packet: string; strategy_profile: string; symbols: string[]; target_evidence: string; }

export interface AgentRunCreateResponse { message: string; run_id: string; status: string; }
